name: Auto Tweet

on:
  schedule:
    - cron: '*/15 * * * *'  # Check every 15 minutes
  workflow_dispatch:

jobs:
  tweet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          pip install tweepy==4.14.0 requests chardet
          echo "Installed packages:"
          pip list
          
      - name: Configure UTF-8 environment
        run: |
          echo "PYTHONUTF8=1" >> $GITHUB_ENV
          echo "PYTHONIOENCODING=utf-8" >> $GITHUB_ENV
          echo "LANG=C.UTF-8" >> $GITHUB_ENV
          echo "LC_ALL=C.UTF-8" >> $GITHUB_ENV
          
      - name: Run Twitter bot
        env:
          API_KEY: ${{ secrets.API_KEY }}
          API_SECRET: ${{ secrets.API_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
          SHEET_URL: ${{ secrets.SHEET_URL }}
          DEFAULT_COMMUNITY: ${{ secrets.DEFAULT_COMMUNITY }}  # Optional
        run: |
          python tweet_bot.py
