name: Auto Tweet

on:
  schedule:
    - cron: '0 8 * * *'  # Daily at 8AM UTC
  workflow_dispatch:

jobs:
  tweet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: pip install tweepy
        
      - name: Debug environment
        run: |
          echo "Current directory: $(pwd)"
          echo "Files:"
          ls -la
          echo "Python version:"
          python --version
          
      - name: Run tweet script
        env:
          API_KEY: ${{ secrets.API_KEY }}
          API_SECRET: ${{ secrets.API_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
        run: |
          python tweet.py || echo "Script failed"
          echo "--- Environment Check ---"
          echo "API_KEY present? ${{ env.API_KEY != '' }}"
          echo "Current date: $(date)"
