name: Auto Tweet

on:
  schedule:
    - cron: '*/15 * * * *'  # Check every 15 minutes
  workflow_dispatch:

jobs:
  tweet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          pip install tweepy==4.14.0 requests chardet
          echo "Installed packages:"
          pip list
          
      - name: Set UTF-8 environment
        run: |
          echo "Setting UTF-8 environment..."
          export LANG=C.UTF-8
          export LC_ALL=C.UTF-8
          export PYTHONIOENCODING=utf-8
          echo "Environment:"
          locale
          
      - name: Run Twitter bot
        env:
          API_KEY: ${{ secrets.API_KEY }}
          API_SECRET: ${{ secrets.API_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
          SHEET_URL: ${{ secrets.SHEET_URL }}
        run: |
          # Force UTF-8 output
          PYTHONUTF8=1 python tweet_bot.py
          
      - name: Upload logs (if needed)
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: debug-logs
          path: |
            *.log
            debug_output.txt
