name: Auto Tweet

on:
  schedule:
    - cron: '*/30 * * * *'  # Check every 30 minutes
  workflow_dispatch:

jobs:
  tweet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: pip install tweepy==4.14.0 requests google-api-python-client google-auth-oauthlib
        
      - name: Run Twitter bot
        env:
          API_KEY: ${{ secrets.API_KEY }}
          API_SECRET: ${{ secrets.API_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
          SHEET_URL: ${{ secrets.SHEET_URL }}
          # Add these if implementing full sheet updating:
          # GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
          # SHEET_ID: ${{ secrets.SHEET_ID }}
        run: python tweet_bot.py
